<?php

use KwantRegistration\App;
use KwantRegistration\Resources\Registration;
use KwantRegistration\I18N\Lang;

/** @var $this Registration */
?>
<!doctype html>
<html lang="en" class="h-100">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Kwant">
  <title>Kwant - <?=Lang::l('Nie znaleziono strony')?></title>
  <link href="<?= App::BaseUrl()?>assets/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="<?= App::BaseUrl()?>css/custom.css" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto"></header>
  <main class="px-3">
    <img class="img-fluid d-block mx-auto mb-4" src="<?= App::BaseUrl()?>assets/brand/logo_kwant.svg" alt="">

    <div class="error-container">
      <div>
        <div class="d-flex mb-3 align-items-center justify-content-center">
          <img class="icon" src="<?= App::BaseUrl()?>assets/images/access-denied-forbidden-icon.svg" alt="" />
          <h1><?=Lang::l('Nie znaleziono strony')?></h1>
        </div>
        <p class="info-text"><?= Lang::l('W przypadku trudności podczas procesu rejestracji, prosimy o kontakt z działem technicznym.')?><br>
          email: <a href="mailto:support@kwant.app" class="info-text-item">support@kwant.app</a> - tel: <span class="info-text-item">00000000</span>
        </p>
      </div>
    </div>

  </main>

  <footer class="mt-auto text-dark-50">
    <p>©2023 <a href="https://www.kwant.net.pl/" target="_blank" class="brand-link">Kwant</a> Hurtownie Elektryczne.<br>All rights reserved.</p>
  </footer>
</div>

<script src="<?= App::BaseUrl()?>assets/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>
